### ISSUE TITLE
all-sites VCF question

### ISSUE THREAD

**Issue by AndreMonc** [harvardinformatics/snpArcher#223]
Hi,

I'm just wanting to check if snpArcher can handle producing all-sites VCFs. From what I can tell, I just need to add the -all-sites flag to the GenotypeGVCFs command in the following two files (or maybe only necessary in the first file?):

1. /snpArcher/workflow/rules/bam2vcf_gatk.smk
2. /snpArcher/workflow/rules/bam2vcf_gatk_intervals.smk

Does that seem right?

Thanks!
Andre

**Comment by erikenbody** [comment]
Hey Andre - that should work, yes. If you have intervals set as "true" in
your config (recommended) then you should only need to add it to the
"intervals" snakemake.

Off the top of my head, I don't think this will affect any downstream
stuff. The annotated filters should all be fine for snps/indels, but you'll
mostly need to go off script for filtering the reference sites in the all
sites VCF. The QC data should be fine though, as that selects SNPs before
running.

We're working on implementing a workaround for all site's VCFs based on the
callable sites file (for windowed analyses), but it's still in development.
So, this is useful motivation!

Erik

**Comment by AndreMonc** [comment]
Thanks, Erik, for the lightning fast response. Super helpful.

That makes sense. Just to summarize, the current snpArcher pipeline has integrated quality filters for SNPs and indels but not for the invariant sites, so I'll need to make sure I include some additional filters for invariant sites on the back end.

For now, I'm thinking that taking the raw final VCF output from snpArcher, separating the invariant sites and variant sites (as recommended here: https://pixy.readthedocs.io/en/latest/guide/pixy_guide.html), doing some additional filtering in bcftools, and then rejoining the VCFs should work to complete the all sites VCF processing pipeline. Sound reasonable?

Great to hear y'all are developing an all-sites feature.

Thanks,
Andre

**Comment by erikenbody** [comment]
Yep that's how I would approach it. If you want to fully take advantage of
the snpArcher filtering, you can run the postprocessing module which will
output a "clean_snps.vcf.gz." To do this, after the initial pipeline
completes, you add a column to the sample sheet with the name "exclude"
then put "Y" for any samples you want to remove (eg after inspecting the QC
plots). Then restart the pipeline and the postprocessing module
<https://github.com/harvardinformatics/snpArcher/blob/main/workflow/modules/postprocess/Snakefile>will
run and make the clean SNPs file. Note you can specify a maf filter in the
config file.

Then all you need to do is manually make a reference sites only vcf from
the "final" vcf, filter it, and merge it with the clean SNPs file for
something pixy friendly.

hope this helps! writing this out - it wouldn't be that hard to implement
as an option, will keep that in mind...
Erik

**Comment by daicy527** [comment]
A little confused. The "final" or "final raw" vcf refers to the vcf generated by the current snpArcher pipeline or by the changed pipeline with adding the -all-sites flag to the GenotypeGVCFs command? Thanks.

**Comment by daicy527** [comment]
Thank you, Erik.

I have added  "-all-sites" into  'bam2vcf_gatk_intervals.smk' and got errors like this: 
==============================
Error in rule DB2vcf:
    jobid: 18434
    input: results/GCA_013397395.1/genomics_db_import/DB_L0723.tar, results/GCA_013397395.1/data/genome/GCA_013397395.1.fna, results/GCA_013397395.1/data/genome/GCA_013397395.1.fna.fai, results/GCA_013397395.1/data/genome/GCA_013397395.1.dict
    output: results/GCA_013397395.1/vcfs/intervals/L0723.vcf.gz, results/GCA_013397395.1/vcfs/intervals/L0723.vcf.gz.tbi
    log: logs/GCA_013397395.1/gatk_genotype_gvcfs/0723.txt (check log file(s) for error details)
    conda-env: /data/snparcher2/snpArcher/.snakemake/conda/9c53882be01c6342dfe89be44d40056f_
    shell:

        tar -xf results/GCA_013397395.1/genomics_db_import/DB_L0723.tar
        gatk GenotypeGVCFs             --java-options '-Xmx29000m -Xms29000m'             -R results/GCA_013397395.1/data/genome/GCA_013397395.1.fna             --heterozygosity 0.005             --genomicsdb-shared-posixfs-optimizations true             -V gendb://results/GCA_013397395.1/genomics_db_import/DB_L0723             -all-sites             -O results/GCA_013397395.1/vcfs/intervals/L0723.vcf.gz             --tmp-dir /data/snpruntem/ZZXQAENGVYOU/ &> logs/GCA_013397395.1/gatk_genotype_gvcfs/0723.txt

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
===================
log file, 0723.txt:

6:28:59.506 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/data/Daichuanyin/snparcher2/snpArcher/.snakemake/conda/9c53882be01c6342dfe89be44d40056f_/share/gatk4-4.1.8.0-0/gatk-package-4.1.8.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Oct 23, 2024 4:28:59 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
16:28:59.949 INFO  GenotypeGVCFs - ------------------------------------------------------------
16:28:59.950 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.1.8.0
16:28:59.950 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
16:28:59.950 INFO  GenotypeGVCFs - Executing as D@ubuntu-PowerEdge-R750 on Linux v5.4.0-150-generic amd64
16:28:59.950 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_382-b05
16:28:59.950 INFO  GenotypeGVCFs - Start Date/Time: October 23, 2024 4:28:59 PM CST
16:28:59.950 INFO  GenotypeGVCFs - ------------------------------------------------------------
16:28:59.950 INFO  GenotypeGVCFs - ------------------------------------------------------------
16:28:59.950 INFO  GenotypeGVCFs - HTSJDK Version: 2.22.0
16:28:59.951 INFO  GenotypeGVCFs - Picard Version: 2.22.8
16:28:59.951 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
16:28:59.951 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:28:59.951 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
16:28:59.951 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:28:59.951 INFO  GenotypeGVCFs - Deflater: IntelDeflater
16:28:59.951 INFO  GenotypeGVCFs - Inflater: IntelInflater
16:28:59.951 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
16:28:59.951 INFO  GenotypeGVCFs - Requester pays: disabled
16:28:59.951 INFO  GenotypeGVCFs - Initializing engine
16:29:01.589 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.0-e701905
16:29:01.762 info  NativeGenomicsDB - pid=26924 tid=26925 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
16:29:01.762 info  NativeGenomicsDB - pid=26924 tid=26925 No valid combination operation found for INFO field MLEAC  - the field will NOT be part of INFO fields in the generated VCF records
16:29:01.762 info  NativeGenomicsDB - pid=26924 tid=26925 No valid combination operation found for INFO field MLEAF  - the field will NOT be part of INFO fields in the generated VCF records
16:29:03.205 INFO  GenotypeGVCFs - Done initializing engine
16:29:03.614 INFO  ProgressMeter - Starting traversal
16:29:03.615 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
16:29:03.668 INFO  GenotypeGVCFs - Shutting down engine
[October 23, 2024 4:29:03 PM CST] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.07 minutes.
Runtime.totalMemory()=29142024192
java.lang.IllegalStateException: There are no sources based on those query parameters
	at org.genomicsdb.reader.GenomicsDBFeatureIterator.<init>(GenomicsDBFeatureIterator.java:167)
	at org.genomicsdb.reader.GenomicsDBFeatureReader.query(GenomicsDBFeatureReader.java:152)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.refillQueryCache(FeatureDataSource.java:567)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.queryAndPrefetch(FeatureDataSource.java:536)
	at org.broadinstitute.hellbender.engine.FeatureDataSource.query(FeatureDataSource.java:502)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$2(VariantLocusWalker.java:149)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:657)
	at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:148)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
Using GATK jar /data/Daichuanyin/snparcher2/snpArcher/.snakemake/conda/9c53882be01c6342dfe89be44d40056f_/share/gatk4-4.1.8.0-0/gatk-package-4.1.8.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx29000m -Xms29000m -jar /data/snparcher2/snpArcher/.snakemake/conda/9c53882be01c6342dfe89be44d40056f_/share/gatk4-4.1.8.0-0/gatk-package-4.1.8.0-local.jar GenotypeGVCFs -R results/GCA_013397395.1/data/genome/GCA_013397395.1.fna --heterozygosity 0.005 --genomicsdb-shared-posixfs-optimizations true -V gendb://results/GCA_013397395.1/genomics_db_import/DB_L0723 -all-sites -O results/GCA_013397395.1/vcfs/intervals/L0723.vcf.gz --tmp-dir /data/snpruntem/ZZXQAENGVYOU/
=======================
What's the problem? Thanks again.

**Comment by tsackton** [comment]
This looks like a bug in GATK with the `all sites` option, see here: https://github.com/broadinstitute/gatk/issues/8415.

**Comment by tsackton** [comment]
There are a few suggested workarounds but it might take a bit of poking around to figure out how to implement them in snpArcher...

**Comment by cademirch** [comment]
Ran into this. Need to give the `-L` option with the interval file. Here is an example rule for all sites vcf:
```
rule DB2vcf_allsites:
    """
    This rule uses the genomic databases from the previous step (gvcf2DB) to create VCF files, one per list file. Thus, lists
    are still scattered.
    """
    input:
        db = "results/{refGenome}/genomics_db_import/DB_L{l}.tar",
        ref = "results/{refGenome}/data/genome/{refGenome}.fna",
        fai = "results/{refGenome}/data/genome/{refGenome}.fna.fai",
        dictf = "results/{refGenome}/data/genome/{refGenome}.dict",
        interval_file = "results/{refGenome}/intervals/db_intervals/{l}-scattered.interval_list"
    output:
        vcf = temp("results/{refGenome}/vcfs/intervals/L{l}.allsites.vcf.gz"),
        vcfidx = temp("results/{refGenome}/vcfs/intervals/L{l}.allsites.vcf.gz.tbi"),
    params:
        het = config['het_prior'],
        db = lambda wc, input: input.db[:-4]
    resources:
        tmpdir = get_big_temp
    log:
        "logs/{refGenome}/gatk_genotype_gvcfs_allsites/{l}.txt"
    benchmark:
        "benchmarks/{refGenome}/gatk_genotype_gvcfs_allsites/{l}.txt"
    conda:
        "../envs/bam2vcf.yml"
    shell:
        """
        tar -xf {input.db}
        gatk GenotypeGVCFs \
            --java-options '-Xmx{resources.mem_mb_reduced}m -Xms{resources.mem_mb_reduced}m' \
            -R {input.ref} \
            --heterozygosity {params.het} \
            --genomicsdb-shared-posixfs-optimizations true \
            --include-non-variant-sites \
            -L {input.interval_file} \
            -V gendb://{params.db} \
            -O {output.vcf} \
            --tmp-dir {resources.tmpdir} &> {log}
        """
  ```

**Comment by AndreMonc** [comment]
Hi everyone, I finally produced an all-sites VCF with snpArcher--this pipeline worked super well! And thanks to all who replied on this thread.

Here are the exact steps I took to make this work:
1) copy and paste Cade's (thank you!!) new "DB2vcf_allsites" rule into the the bam2vcf_gatk_intervals.smk file (.../snpArcher/workflow/rules/bam2vcf_gatk_intervals.smk)
2) update the filterVcfs rule inputs (in the same bam2vcf_gatk_intervals.smk file) for vcf and vcfidx so that they correspond to the output from the DB2vcf_allsites rule (just add "allsites").
3) update each instance of the DB2vcf rule to DB2vcf_allsites in the slurm config file
4) Perhaps because of carry-over from my old version of the slurm config file, but I ran into a "clam_loci" rule error. What fixed this was explicitly assigning more resources for the clam_loci rule in my slurm config file:
set-resources:
  clam_loci:
    mem_mb: attempt * 64000
    mem_mb_reduced: (attempt * 64000) * 0.9 # Mem allocated to java (tries to prevent OOM errors)
    slurm_partition: "single"
    slurm_account: "NAME_OF_HPC_ALLOCATION" # Same as sbatch -A. Not all clusters use this.
    runtime: 4320
    cpus_per_task: 16
set-threads:
  clam_loci: 16

After a little trial and error with memory issues, I also explicitly boost computational resources for various other rules. If anyone want to get an allsites VCF, I'm happy to share my full config.yaml file. Just send me an email.

Cheers,
Andre
